### ISSUE TITLE
Streaming Merge Checklist

### ISSUE THREAD

**Issue by braceal** [DeepDriveMD/DeepDriveMD-pipeline#38]
Here is an ongoing list of todos and generalizations needed before we can merge support for streaming to the main branch.

The main point is to first make the code as simple as possible and reuse as many functions as possible from the main branch.

If needed, separate issues can be made to discuss these (or the discussion can stay here if it is a simple issue).

- [ ] Remove all unused code (Including md5 sum logic, unused functions, etc)
- [ ] All parameters should be in the config (no hard coded values) e.g. the simulation temperature in run_openmm.py
- [ ] Support optional contact map, rmsd computations
- [ ] A function to write an arbitrary numpy array to an adios stream
- [ ] Support for multiple input PDB files
- [ ] Support for PDB and topology files for starting and managing OpenMM simulations
- [ ] Put parse_args in DDMD utils
- [ ] Update subprocess calls to shutil and pathlib where possible e.g. shutil.move() for moving a file
- [ ] Update code style with black and flake8 (Alex can do this)
- [ ] Documentation explaining how to install and run

Future generalizations/improvements to keep in mind (not necessarily needed for a merge):

 - [ ] Make adios xml file parameters configurable
 - [ ] Backing up old model checkpoints
 - [ ] Adding post analysis codes as a function library
 - [ ] Add function for plotting sampling effectiveness given embeddings

**Comment by braceal** [comment]
#39 Addresses this. Closing this issue.
