### ISSUE TITLE
Next release v0.0.3

### ISSUE THREAD

**Issue by braceal** [DeepDriveMD/DeepDriveMD-pipeline#49]
**Required**

- [ ] Test support for the latest version of h5py to see if we can remove dependence on 2.10.0 @braceal 
- [ ] Create a conda release (may not be necessary with singularity)
- [ ] Build a singularity container for each HPC platform (Summit/Lassen to start) @igory1999 
- [x] Merge branch `feature/psc_bridges2` #48 @braceal 
- [ ] Merge branch `feature/radical_session_directory` #40 @braceal 
- [x] Change all instances of `schema` to `access_schema` when creating a radical.entk application @braceal 
- [ ] Rework yaml schema to remove "set_by_deepdrivemd" options from the user level. @braceal 
- [x] When updating yaml schema, change `schema_` parameter to `access_schema`.  @braceal
- [x] Tutorials for streaming usage in the docs containing explanation of how to use the software/what it does/analyzing results @igory1999 
- [ ] Add documentation for each input parameter #42 @braceal @igory1999 
- [ ] Add specific documentation to address #34 @braceal
